### ISSUE TITLE
simple-tls插件不是此平台可执行程序

### ISSUE THREAD

**Issue by Meilinhost** [IrineSistiana/simple-tls#12]
![捕获.PNG](https://i.loli.net/2020/07/13/lCzi79gaFHM2dtJ.png)

**Comment by cyqsimon** [comment]
Are you using 32 bit windows?

**Comment by xidcn** [comment]
Yes, I am using 32-bit Windows

**Comment by IrineSistiana** [comment]
32位的电脑不能用64位的文件。

你用了64位的二进制文件。
