### ISSUE TITLE
有计划支持 MUX 多路复用吗？

### ISSUE THREAD

**Issue by CrazyBoyFeng** [IrineSistiana/simple-tls#17]
以前的 mos-tls-tunnel 是有这个功能的。simple-tls 似乎没有了。
MUX 可以避免频繁连接，从而避免被机房或 CDN 的防火墙判为 DDoS，同时也能减少频繁尝试握手的资源开销。

**Comment by IrineSistiana** [comment]
mux 的话， v2ray plugin 的实现性能更好。所以 simple-tls 去掉了。
