### ISSUE TITLE
Consider removing default timeout?

### ISSUE THREAD

**Issue by cyqsimon** [IrineSistiana/simple-tls#18]
[Quote from cbeuw](https://github.com/cbeuw/Cloak/releases/tag/v2.4.0):
> StreamTimeout is now no longer an option on Cloak server as Cloak will no longer timeout connections after at least some data has been sent. Connection timeout behaviours should be entirely implemented by the underlying proxy program. See shadowsocks/shadowsocks-rust#343.

Should simple-tls too consider unsetting its default timeout of 300s, or perhaps removing the option altogether?

**Comment by IrineSistiana** [comment]
Thanks for the advice.

However, I disagree with them.

Timeout is the basic method to prevent resource leak. It should be implemented in every protocol and layer. It can be very long, but it cannot be none.

Therefore, the `timeout` option in simple-tls won't be changed.
