### ISSUE TITLE
xtls?

### ISSUE THREAD

**Issue by delphinuz** [IrineSistiana/simple-tls#20]
![test](https://user-images.githubusercontent.com/615043/102344968-9f6a6280-3fd7-11eb-863e-51cf4e20ecfe.png)

考虑多支持xtls吗？ 测试一下，上方ss(md4rc5)+simple-tls(关pd)，中间是xray(xtls)，下方是ss(md4rc5)+simple-tls(关pd)。

因为已有tls，所以ss使用md4rc5。

**Comment by IrineSistiana** [comment]
感谢建议。

但很遗憾，不行。

xtls 要求下层连接的 tls 不能被修改。

ss + simple-tls，下层连接被 ss 加密过了。xtls 不会有作用。

**Comment by delphinuz** [comment]
有点怪，按理应是 data ->ss(第一次加密)->simple-tls(建立tls加密通道，第二次加密) ------------->simple-tls(tls第一次解密)-->ss(第二次解密)，所以xtls应是取代tls(xtls也相容tls)，与ss应是无关的。
