### ISSUE TITLE
Tutorial , please .

### ISSUE THREAD

**Issue by ingnelson** [IrineSistiana/simple-tls#5]
Hello . Can you create a tutorial how to install and run this plugin once I install shadowsocks in the UBUNTU VPS, please .
Or just the command or a script, please
Or upload a full gif video or a YouTube video .

 I just downloaded the apk and install it on my Android .
I am not a programmer , but I like shadowsocks and I would like to use your plugin.

I hope you answer.

**Comment by IrineSistiana** [comment]
Unfortunately, a tutorial is not a easy thing. It depends on which kind of shadowsock server and OS system you are using and how you gonna use.
