### ISSUE TITLE
[Suggestion] Add note on TLS mode and WSS mode?

### ISSUE THREAD

**Issue by cyqsimon** [IrineSistiana/simple-tls#9]
Can you please make a recommendation in the documentation on which mode is preferable?

As per my understanding, WSS should be preferred because it is full-duplex, but I am not sure whether this is the case for your software. It would be best to have a recommendation from the author.

Thanks.

**Comment by IrineSistiana** [comment]
Hi @cyqsimon 

It's depand on your Internet environment and your purpose. 

I prefer to not leaving a recommendation and let users make their own independent choices.

If you don't know which mode to use, you can try both tls and wss and see which is more suitable for you.

**Comment by cyqsimon** [comment]
Okay, thank you.
